definitions:
  api.MSG_RESP_HEALTH:
    properties:
      unixtime:
        type: integer
    type: object
info:
  contact:
    email: contact@domain.com
    name: Support
    url: https://domain.com
  description: api example
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://domain.com
  title: api example
  version: "1.0"
paths:
  /api/health:
    get:
      description: health check
      produces:
      - application/json
      responses:
        "200":
          description: server unix time
          schema:
            $ref: '#/definitions/api.MSG_RESP_HEALTH'
      summary: /api/health
      tags:
      - health
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
