end_point = "https://api.meson.network"
https_port = 443
log_level = "INFO"
token = ""

[cache]
  folder = "./m_cache"
  size = 30

[storage]
  enable = true
  api_port = 10443
  console_port = 10444
  folder = "./m_storage"
  password = ""
