daemon_name = 'meson-node'
log_level = 'INFO'
token =''
https_port = 0
end_point='https://api.meson.network'

[cache]
enable = true
folder ="./m_cache"
size_BG = 0

[storage]
enable = true
api_port = 10443
console_port = 10444
folder="./m_storage"
password=''