end_point = "https://api.cdn.meson.network"
https_port = 443
token = ""

upgrade_keep=[
  "https_port",
  "token",
  "cache.folder",
  "cache.size",
  "storage.enable",
  "storage.api_port",
  "storage.console_port",
  "storage.folder",
  "storage.password",
]

[log]
level = "INFO"

[cache]
  folder = "./m_cache"
  size = 30

[storage]
  enable = true
  api_port = 10443
  console_port = 10444
  folder = "./m_storage"
  password = ""

